function combinedPlot()
% combinedPlot - Generate a two-panel Floquet phase diagram.
%
% This script loads the diffusion-map results from the J2 and J3 scans and
% creates a publication-style figure with phase regions, topological
% invariant insets, eigenvalue insets, and PCA insets.
%
% Expected input files:
%   ./results/2DD1.mat   Results from the J2 scan script
%   ./results/2DD2.mat   Results from the J3 scan script
%
% The script also falls back to files in the current working directory if the
% ./results directory does not exist or does not contain the required files.

figure('Position', [100, 100, 1000, 520], ...
       'Color', 'w', ...
       'Name', 'Floquet Phase Diagram', ...
       'NumberTitle', 'off');

set(gcf, 'DefaultAxesFontName', 'Times New Roman');
set(gcf, 'DefaultTextFontName', 'Times New Roman');

dataDir = fullfile(pwd, 'results');
j2DataFile = resolveDataFile('2DD1.mat', dataDir);
j3DataFile = resolveDataFile('2DD2.mat', dataDir);

dataJ2 = load(j2DataFile, 'eigvals', 'score', 'V_sym');
dataJ3 = load(j3DataFile, 'eigvals', 'score', 'V_sym');

% Panel (a): J2 scan.
axA = subplot(1, 2, 1);
plotJ2ScanPanel(axA, dataJ2.eigvals, dataJ2.score);
text(axA, -0.15, 1.05, '(a)', ...
     'Units', 'normalized', ...
     'FontSize', 27, ...
     'FontWeight', 'bold', ...
     'FontName', 'Times New Roman');

% Panel (b): J3 scan.
axB = subplot(1, 2, 2);
plotJ3ScanPanel(axB, dataJ3.eigvals, dataJ3.score);
text(axB, -0.15, 1.05, '(b)', ...
     'Units', 'normalized', ...
     'FontSize', 27, ...
     'FontWeight', 'bold', ...
     'FontName', 'Times New Roman');
end

function filePath = resolveDataFile(fileName, dataDir)
% resolveDataFile - Locate a required MAT file using GitHub-friendly paths.

candidate = fullfile(dataDir, fileName);

if isfile(candidate)
    filePath = candidate;
elseif isfile(fileName)
    filePath = fileName;
else
    error(['Required data file not found: %s\n' ...
           'Expected either "%s" or "%s".'], ...
           fileName, candidate, fullfile(pwd, fileName));
end
end

function plotJ2ScanPanel(ax, eigvals, score)
% plotJ2ScanPanel - Plot the phase diagram and insets for the J2 scan.

edges = 0:1:5;
numPhases = 5;
colors = lines(numPhases);

% Each two-digit label encodes the pair (W0, Wpi).
phaseLabels = {'10', '12', '32', '34', '54'};
W0 = zeros(1, numPhases);
Wpi = zeros(1, numPhases);

for phaseIdx = 1:numPhases
    invariants = sscanf(phaseLabels{phaseIdx}, '%1d%1d');
    W0(phaseIdx) = invariants(1);
    Wpi(phaseIdx) = invariants(2);
end

hold(ax, 'on');

yLimits = [-1.2, 1.2];
ylim(ax, yLimits);

for phaseIdx = 1:numPhases
    patch(ax, ...
          [edges(phaseIdx), edges(phaseIdx), edges(phaseIdx + 1), edges(phaseIdx + 1)], ...
          [yLimits(1), yLimits(2), yLimits(2), yLimits(1)], ...
          colors(phaseIdx, :), ...
          'FaceAlpha', 0.25, ...
          'EdgeColor', 'none');
end

formatMainAxis(ax);
xlim(ax, [0, 5]);
set(ax, ...
    'XTick', edges, ...
    'XTickLabel', {'0', '1', '2', '3', '4', '5'}, ...
    'FontSize', 27, ...
    'TickLabelInterpreter', 'latex');
set(ax, 'YTick', []);
axis(ax, 'square');
xlabel(ax, '$J_2/\pi$', ...
       'Interpreter', 'latex', ...
       'FontSize', 30, ...
       'Color', 'k');

mainPosition = get(ax, 'Position');

% Inset: topological invariants.
curveHeight = 0.12;
axInvariant = axes('Position', ...
                   [mainPosition(1), ...
                    mainPosition(2) + mainPosition(4) - curveHeight - 0.20, ...
                    mainPosition(3), ...
                    curveHeight], ...
                   'Box', 'on', ...
                   'Color', 'none');
hold(axInvariant, 'on');

[xPlot, W0Plot] = makeStepData(edges, W0);
[~, WpiPlot] = makeStepData(edges, Wpi);

stairs(axInvariant, xPlot, W0Plot, '-', ...
       'LineWidth', 3, ...
       'Color', [0.8, 0.2, 0.2]);
stairs(axInvariant, xPlot, WpiPlot, '--', ...
       'LineWidth', 3, ...
       'Color', [0.2, 0.2, 0.8]);

legend(axInvariant, {'$W_0$', '$W_\pi$'}, ...
       'Location', 'northeast', ...
       'FontSize', 15, ...
       'Interpreter', 'latex', ...
       'Box', 'on');

set(axInvariant, ...
    'XTick', [], ...
    'YTick', [1, 3, 5], ...
    'FontSize', 15, ...
    'TickLabelInterpreter', 'latex');
ylim(axInvariant, [min([W0, Wpi]) - 0.5, max([W0, Wpi]) + 1.5]);
xlim(axInvariant, [0, 5]);
ylabel(axInvariant, '$W_0,W_\pi$', ...
       'Interpreter', 'latex', ...
       'FontSize', 20);
text(axInvariant, 2.5, 7.3, '$\mathrm{invariants}$', ...
     'Interpreter', 'latex', ...
     'FontSize', 14, ...
     'HorizontalAlignment', 'center');

% Inset: leading diffusion-map eigenvalues.
axEig = axes('Position', ...
             [mainPosition(1) + 0.06, mainPosition(2) + 0.25, 0.09, 0.09]);
plotEigenvalueInset(axEig, eigvals);

% Inset: PCA scatter plot.
axPca = axes('Position', ...
             [mainPosition(1) + mainPosition(3) - 0.14, mainPosition(2) + 0.25, 0.09, 0.09]);
plotPcaInset(axPca, score, colors, numPhases, [-0.3, 0.3], [-0.4, 0.4]);
end

function plotJ3ScanPanel(ax, eigvals, score)
% plotJ3ScanPanel - Plot the phase diagram and insets for the J3 scan.

delta = 1 / 3;
xMax = 7 / 3;
edges = 0:delta:xMax;
numRegions = 7;
colors = lines(numRegions);

% Columns: W0, Wpi, G0, Gpi.
topologicalData = [ ...
     1,  0, 1, 0; ...
     1, -1, 1, 1; ...
     0, -1, 2, 1; ...
     0,  1, 2, 3; ...
    -1,  1, 3, 3; ...
    -1,  0, 3, 4; ...
     1,  0, 5, 4];

W0 = topologicalData(:, 1).';
Wpi = topologicalData(:, 2).';
G0 = topologicalData(:, 3).';
Gpi = topologicalData(:, 4).';

hold(ax, 'on');

yLimits = [-1.2, 1.2];
ylim(ax, yLimits);

for regionIdx = 1:numRegions
    patch(ax, ...
          [edges(regionIdx), edges(regionIdx), edges(regionIdx + 1), edges(regionIdx + 1)], ...
          [yLimits(1), yLimits(2), yLimits(2), yLimits(1)], ...
          colors(regionIdx, :), ...
          'FaceAlpha', 0.25, ...
          'EdgeColor', 'none');
end

formatMainAxis(ax);
xlim(ax, [0, xMax]);
set(ax, ...
    'XTick', edges, ...
    'XTickLabel', {'$0$', '$1/3$', '$2/3$', '$1$', '$4/3$', '$5/3$', '$2$', '$7/3$'}, ...
    'FontSize', 23, ...
    'TickLabelInterpreter', 'latex');
set(ax, 'YTick', []);
axis(ax, 'square');
xlabel(ax, '$J_3/\pi$', ...
       'Interpreter', 'latex', ...
       'FontSize', 30, ...
       'Color', 'k');

mainPosition = get(ax, 'Position');

curveHeight = 0.12;
curveGap = 0.03;

[xPlot, W0Plot] = makeStepData(edges, W0);
[~, G0Plot] = makeStepData(edges, G0);
[~, WpiPlot] = makeStepData(edges, Wpi);
[~, GpiPlot] = makeStepData(edges, Gpi);

% Inset: 0-gap invariants.
axZeroGap = axes('Position', ...
                 [mainPosition(1), ...
                  mainPosition(2) + mainPosition(4) - curveHeight - 0.15, ...
                  mainPosition(3), ...
                  curveHeight], ...
                 'Box', 'on', ...
                 'Color', 'none');
hold(axZeroGap, 'on');

stairs(axZeroGap, xPlot, W0Plot, '-', ...
       'LineWidth', 3, ...
       'Color', [0.8, 0.2, 0.2]);
stairs(axZeroGap, xPlot, G0Plot, '--', ...
       'LineWidth', 3, ...
       'Color', [0.2, 0.8, 0.2]);

legend(axZeroGap, {'$W_0$', '$G_0$'}, ...
       'Location', 'northeast', ...
       'FontSize', 15, ...
       'Interpreter', 'latex', ...
       'Box', 'on');

set(axZeroGap, ...
    'XTick', [], ...
    'YTick', [0, 2, 4], ...
    'FontSize', 15);
ylim(axZeroGap, [min([W0, G0]) - 0.5, max([W0, G0]) + 1.5]);
xlim(axZeroGap, [0, xMax]);
ylabel(axZeroGap, '$W_0,G_0$', ...
       'Interpreter', 'latex', ...
       'FontSize', 20);
text(axZeroGap, xMax / 2, 7.3, '$\mathrm{0\ gap\ invariants}$', ...
     'Interpreter', 'latex', ...
     'FontSize', 13, ...
     'HorizontalAlignment', 'center');

% Inset: pi-gap invariants.
axPiGap = axes('Position', ...
               [mainPosition(1), ...
                mainPosition(2) + mainPosition(4) - 2 * curveHeight - curveGap - 0.20, ...
                mainPosition(3), ...
                curveHeight], ...
               'Box', 'on', ...
               'Color', 'none');
hold(axPiGap, 'on');

stairs(axPiGap, xPlot, WpiPlot, '-', ...
       'LineWidth', 3, ...
       'Color', [0.2, 0.2, 0.8]);
stairs(axPiGap, xPlot, GpiPlot, '--', ...
       'LineWidth', 3, ...
       'Color', [0.8, 0.5, 0.2]);

legend(axPiGap, {'$W_\pi$', '$G_\pi$'}, ...
       'Location', 'northeast', ...
       'FontSize', 15, ...
       'Interpreter', 'latex', ...
       'Box', 'on');

set(axPiGap, ...
    'XTick', [], ...
    'YTick', [0, 2, 4], ...
    'FontSize', 15);
ylim(axPiGap, [min([Wpi, Gpi]) - 0.5, max([Wpi, Gpi]) + 1.5]);
xlim(axPiGap, [0, xMax]);
ylabel(axPiGap, '$W_\pi,G_\pi$', ...
       'Interpreter', 'latex', ...
       'FontSize', 20);
text(axPiGap, xMax / 2, 6.5, '$\mathrm{\pi\ gap\ invariants}$', ...
     'Interpreter', 'latex', ...
     'FontSize', 13, ...
     'HorizontalAlignment', 'center');

% Inset: leading diffusion-map eigenvalues.
axEig = axes('Position', ...
             [mainPosition(1) + 0.07, mainPosition(2) + 0.20, 0.09, 0.09]);
plotEigenvalueInset(axEig, eigvals);

% Inset: PCA scatter plot.
axPca = axes('Position', ...
             [mainPosition(1) + mainPosition(3) - 0.13, mainPosition(2) + 0.20, 0.09, 0.09]);
plotPcaInset(axPca, score, colors, numRegions, [-0.5, 0.5], [-0.5, 0.5]);
end

function formatMainAxis(ax)
% formatMainAxis - Apply shared formatting to the main phase diagram axes.

set(ax, ...
    'LineWidth', 2, ...
    'Box', 'on', ...
    'XColor', [0.5, 0.5, 0.5], ...
    'YColor', [0.5, 0.5, 0.5], ...
    'Layer', 'top');

ax.XAxis.TickLabelColor = 'k';
ax.YAxis.TickLabelColor = 'k';
end

function [xPlot, yPlot] = makeStepData(edges, values)
% makeStepData - Convert piecewise-constant values to stair-plot vectors.

xPairs = [edges(1:end-1); edges(2:end)];
xPlot = xPairs(:).';
yPlot = repelem(values, 2);
end

function plotEigenvalueInset(ax, eigvals)
% plotEigenvalueInset - Plot the leading diffusion-map eigenvalues.

numEigvals = min(10, numel(eigvals));
eigvalIdx = 1:numEigvals;
eigvalAbs = abs(eigvals(eigvalIdx));

plot(ax, eigvalIdx, eigvalAbs, 'o', ...
     'Color', [0.25, 0.75, 0.95], ...
     'MarkerFaceColor', [0.25, 0.75, 0.95], ...
     'LineWidth', 0.5, ...
     'MarkerSize', 4);

if max(eigvalAbs) > 0
    ylim(ax, [0, 1.1 * max(eigvalAbs)]);
end

xlabel(ax, '$n$', ...
       'Interpreter', 'latex', ...
       'FontSize', 15);
ylabel(ax, '$\lambda_n$', ...
       'Interpreter', 'latex', ...
       'FontSize', 15);
box(ax, 'on');
set(ax, 'FontSize', 15);
end

function plotPcaInset(ax, score, colors, numGroups, xLimits, yLimits)
% plotPcaInset - Plot grouped PCA coordinates in a small inset.

hold(ax, 'on');

pc2 = score(:, 2);
pc3 = score(:, 3);
numSamples = size(score, 1);
groupSize = numSamples / numGroups;

for groupIdx = 1:numGroups
    sampleIdx = (groupIdx - 1) * groupSize + 1 : groupIdx * groupSize;
    plot(ax, pc2(sampleIdx), pc3(sampleIdx), 'o', ...
         'Color', colors(groupIdx, :), ...
         'MarkerFaceColor', colors(groupIdx, :), ...
         'MarkerSize', 4);
end

xlim(ax, xLimits);
ylim(ax, yLimits);
xlabel(ax, 'PC2', 'FontSize', 15);
ylabel(ax, 'PC3', 'FontSize', 15);
box(ax, 'on');
set(ax, 'FontSize', 15);
end
